### ISSUE TITLE
Aggiungere lang nelle descrizioni delle classifiche o tipi di evento

### ISSUE THREAD

**Issue by LewentalDigital** [Gruppo-TecWeb/Codice#114]
sia in fungo che micelio
battle non ha il lang en

**Comment by abenetazzo** [comment]
Attenzione, da valutare bene secondo me... Si potrebbe fare come hanno fatto quelli di Pop Tech, ovvero prevedendo dei tag personalizzati, semplici da usare per l'utente, e spiegando nei vari form come utilizzarli, per poi gestirli da php. Non saprei come mantenere la completa separazione php-html, nemmeno loro l'hanno fatto (hanno messo lo span nel php).
