### ISSUE TITLE
Arricchire descrizioni eventi nel db 

### ISSUE THREAD

**Issue by rzaupa** [Gruppo-TecWeb/Codice#121]
Al momento le informazioni presenti sugli eventi sono un po' povere, sarebbe meglio aggiungere delle descrizioni piu' dettagliate ed informative (magari sulle modalità della serata). 
Ad esempio meal the mic ha solo come descrizione "rapcolta alimentare" che vuol dire tutto e niente

**Comment by abenetazzo** [comment]
> E anche le immagini degli eventi sono tutte uguali, la pagina eventi è un po triste Mettendo immagini diverse mostra la pagina eventi nel suo splendore, si può fare?

Certo che si può fare, ma quali immagini metto?

**Comment by abenetazzo** [comment]
> Al momento le informazioni presenti sugli eventi sono un po' povere, sarebbe meglio aggiungere delle descrizioni piu' dettagliate ed informative (magari sulle modalità della serata). Ad esempio meal the mic ha solo come descrizione "rapcolta alimentare" che vuol dire tutto e niente

Le modalità della serata vengono decise durante la serata stesa, quindi sicuramente non si potrebbe fare per le serate programmate, solamente per le serate già occorse. Il punto è che sarebbe per loro una cosa in più da segnarsi e da mettere nel sito, ho qualche dubbio che lo farebbero...
Comunque ditemi voi, cosa potremmo mettere secondo voi?

**Comment by abenetazzo** [comment]
Ho trovato un po' di materiale, date un'occhiata alla pull request.
