### ISSUE TITLE
In eventi quando vai sopra il selettore di date navigando con la freccia dice "barra pulsante spin zero barra pulsante spin zero" e non è carino

### ISSUE THREAD

**Issue by T-Brex** [Gruppo-TecWeb/Codice#131]
Potresti risolvere mettendo un aria-hidden su input#data e metti un span class="navigationHelp" in cui scrivi selezione per giorno,mese,anno o da calendario.. non so, poi vedi tu

**Comment by rzaupa** [comment]
è correlata alla issue #323
