### ISSUE TITLE
La riproduzione automatica in beats deve diventare una checkbox

### ISSUE THREAD

**Issue by T-Brex** [Gruppo-TecWeb/Codice#134]

**Comment by T-Brex** [comment]
Non è una checkbox, funziona come un normale bottone!

**Comment by LewentalDigital** [comment]
Dato che si tratta di un bottone che indica uno stato possiamo farlo diventare un toggle button

Applicare gli accorgimenti indicati qui riguardo il toggle:
https://www.w3.org/WAI/ARIA/apg/patterns/button/

**Comment by LewentalDigital** [comment]
Ho visto che hai già implementato aria-pressed, ma al caricamento della pagina non è presente, arriva solo quando lo clicco, puoi fare in modo che ci sia sempre?

**Comment by T-Brex** [comment]
in teoria è risolto agggiungendo aria-pressed="false" nell'html
