### ISSUE TITLE
Rimuovere titoli evento dal select nel filtro del tipo evento

### ISSUE THREAD

**Issue by LewentalDigital** [Gruppo-TecWeb/Codice#138]
Il filtro nela pagina eventi dovrebbe filtrare per tipo di eventi, non per titolo, attualmente nel select appaiono i titoli, rimuoverli e far si che appaiano solo i tipi di evento

**Comment by rzaupa** [comment]
Non ho capito il problema , ora non è per tipo ?

**Comment by LewentalDigital** [comment]
> Non ho capito il problema , ora non è per tipo ?

No, prova tu, quando apro la select mi vengono proposti tutti i titoli degli eventi, non i tipi

**Comment by rzaupa** [comment]
Nel Db ciò che si intende per tipo evento corrisponde a "micelio" e "Fungo" e basta, volevi questo ?

**Comment by LewentalDigital** [comment]
> Nel Db ciò che si intende per tipo evento corrisponde a "micelio" e "Fungo" e basta, volevi questo ?

Sì, se quello a cui ti riferisci è il titolo del TipoEvento e NON al titolo dell'Evento

**Comment by rzaupa** [comment]
Non sono d'accordo, un evento di tipo "Meal the mic" come è raggiungibile dall'utente in questo modo ? Mettere solo i tipi evento (che saranno sempre e solo 2) rende poi il filtro poco significativo

**Comment by LewentalDigital** [comment]
Mica tutto deve essere raggiungibile dall'utente in qualsiasi modo, questa select è un filtro, che senso ha mostrare ogni titolo di ogni evento?
E quando avranno pubblicato 100 eventi? verrà mostrata la select con 100 voci? (anche se la maggior parte saranno eventi fungo e micelio, e 20 no, 22 voci in una select è irragionevole)
La pagina degli eventi è già una lista in sé

**Comment by LewentalDigital** [comment]
Come accordato dal vivo, va implementato solo per il tipo evento
Proposta di bre: aggiungere nel select **Altro**, che restituisce tutto ciò che non è un tipo evento definito

**Comment by LewentalDigital** [comment]
Rimuovere anche dalla pagina eventi le funzioni "htmlspecialchars" che rimuovono l'encoding delle cose prese dal database
Non sono necessarie perchè il dato va preso dal DB (e il controllo inserimento avrà già agito sui caratteri speciali")
