### ISSUE TITLE
Implementare tag picture per Eventi ed Evento

### ISSUE THREAD

**Issue by LewentalDigital** [Gruppo-TecWeb/Codice#163]
Quando non è presente una locandina di un evento bisogna mostrare comunque qualcosa, ho pensato all'iconcina del fungo (che ne dici?)

La prima cosa che mi è venuta in mente è usare il tag picure (come hanno fatto i malandrini di soundstage)

**Comment by abenetazzo** [comment]
> Quando non è presente una locandina di un evento bisogna mostrare comunque qualcosa, ho pensato all'iconcina del fungo (che ne dici?)
> 
> La prima cosa che mi è venuta in mente è usare il tag picure (come hanno fatto i malandrini di soundstage)

non credo che il tag picture sia la soluzione al nostro problema, o meglio sarebbe un uso improprio di questo tag secondo me... dalla documentazione (https://www.w3schools.com/tags/tag_picture.asp) si legge che l'uso più comune di questo tag è legato al responsive design, per poter utilizzare immagini diverse (con risoluzione diversa) in base alla grandezza dello schermo, in modo ad esempio di non dover caricare un'immagine ad alta risoluzione per una visualizzazione da mobile, quando ne basta una molto più leggera.

e se gestissimo la cosa semplicemente a livello logico, ovvero tenendo un'immagine di default nel database al posto del valore NULL?
