### ISSUE TITLE
Rimuovere funzionalità che aspetta il caricamento di js in Beats

### ISSUE THREAD

**Issue by LewentalDigital** [Gruppo-TecWeb/Codice#165]
Per favorire gli utenti che non usano js abbiamo fatto si che Beats funzioni anche senza di esso, ma ciò peggiora l'esperienza quando il caricamento di js avviene lentamente.
Rimuovere questa funzionalità è una sofferenza necessaria
Rimuovere ovviamente anche tutto l'html in eccesso

Questa pagina funzionerà solo per gli utilizzatori di javascript

Se si hanno idee migliori, dirle pure (https://byteofdev.com/posts/speed-up-javascript-loading/)

**Comment by T-Brex** [comment]
eliminata funzionalità
