### ISSUE TITLE
Funzione elimina il mio profilo per utenti A admin e U normali

### ISSUE THREAD

**Issue by LewentalDigital** [Gruppo-TecWeb/Codice#170]
L'eliminazione **NON** deve rimuovere completamente l'utente dal database, ma rimuovere i suoi dati sensibili come  email/foto e lasciare quelli che saranno visualizzati nelle classifiche
Così le attività passate dell'utente rimangono

Criticità: se un utente elimina il suo profilo, il suo nome rimane nel db, allora non sarà più disponibile come nome, come fare?? 
Possibile soluzione: quando elimino il mio profilo, il nome viene cambiato a: nome (profilo eliminato)
Che ne dici?

**Comment by abenetazzo** [comment]
issue inclusa in #168
