### ISSUE TITLE
Breadcrumbs Evento con nome dell' Evento

### ISSUE THREAD

**Issue by LewentalDigital** [Gruppo-TecWeb/Codice#171]
Cambiare il funzionamento delle breadcrumbs della pagina Evento mostrando il nome dell'Evento al posto della stringa "Evento"

Nessuna composizione strana con le date, titolo dell'evento e basta

**Comment by rzaupa** [comment]
Poi l'utente viene disorientato ! 👎

**Comment by LewentalDigital** [comment]
> Poi l'utente viene disorientato ! 👎

Che ne dici di fare un controllo: se il titolo dell'evento è uguale al titolo del tipo evento allora mettiamo la data; altrimenti solo il titolo dell'evento
Esempio: Fungo 30/04/24; con evento di tipo Fungo
oppure: Meal the mic.; con evento senza tipo
oppure: Fungo edizione Malaria; con evento di tipo Fungo

**Comment by rzaupa** [comment]
> > Poi l'utente viene disorientato ! 👎
> 
> Che ne dici di fare un controllo: se il titolo dell'evento è uguale al titolo del tipo evento allora mettiamo la data; altrimenti solo il titolo dell'evento Esempio: Fungo 30/04/24; con evento di tipo Fungo oppure: Meal the mic.; con evento senza tipo oppure: Fungo edizione Malaria; con evento di tipo Fungo

Non mi è ben chiaro, nelle breadcrumb metteresti il nome dell'evento o il tipo ?
Per Meal the mic :
Home >> Eventi >> Meal the Mic ?

**Comment by LewentalDigital** [comment]
> > > Poi l'utente viene disorientato ! 👎
> > 
> > 
> > Che ne dici di fare un controllo: se il titolo dell'evento è uguale al titolo del tipo evento allora mettiamo la data; altrimenti solo il titolo dell'evento Esempio: Fungo 30/04/24; con evento di tipo Fungo oppure: Meal the mic.; con evento senza tipo oppure: Fungo edizione Malaria; con evento di tipo Fungo
> 
> Non mi è ben chiaro, nelle breadcrumb metteresti il nome dell'evento o il tipo ? Per Meal the mic : Home >> Eventi >> Meal the Mic ?

Un ibrido: 
se nome evento === tipo evento => allora nelle breadcrumbs metto nome + data
altrimenti metto solo il nome

**Comment by LewentalDigital** [comment]
Implementare con Titolo e basta
