### ISSUE TITLE
Rivedere la formazione del link URI per la pagina classifiche

### ISSUE THREAD

**Issue by rzaupa** [Gruppo-TecWeb/Codice#177]
Ad esempio un link tipo "classifiche.php?classifica=Micelio%7B.%7D2023-11-07&form_submit="
non ha senso , lo andrei a formattare meglio in modo che da altre pagine sia possibile ricostruirlo in automatico, ad esempio per la pagina evento il filtro viene creato in questo modo "eventi.php?data=&titolo=Micelio" quando si cerca per titolo ma non per data, è facilmente ricostruibile.  Inoltre per l'utente non è il massimo condividere un link così per le classifiche.

**Comment by abenetazzo** [comment]
Risolto nella pull request collegata, in attesa di una tua revisione per il merge.

**Comment by rzaupa** [comment]
risolta in #185
