### ISSUE TITLE
Cambio bottone elimina in annulla se sto creando nuova entry in area admin

### ISSUE THREAD

**Issue by LewentalDigital** [Gruppo-TecWeb/Codice#187]
Attualmente durante la creazione di un nuovo evento/classifica/tipo evento/rapper/amministratore vedo il bottone elimina, ma non esiste ancora la cosa che sto creando

Far si che se sto creando una nuova entry, il testo del bottone mostri 'Annulla' al posto di elimina

**Comment by abenetazzo** [comment]
Nascondere button "Elimina" in caso di Aggiunta, modificare button "Torna a..." in "Annulla"
