### ISSUE TITLE
Assicurarsi che le funzionalità create con JavaScript siano disponibili anche se lo script viene bloccato o non viene caricato

### ISSUE THREAD

**Issue by LewentalDigital** [Gruppo-TecWeb/Codice#20]
Se il js creato sostituisce un bottone allora tenere comunque il bottone e nascondelo con js al suo caricamento (informarsi sul modo adatto per farlo)
Se il js permette di mostrare contenuto occulto, creare un metodo alternativo per rivelarlo o metterlo visibile di default; e al caricamento del js nasconderlo 
### (chiedi a seb per chiarimenti)

**Comment by abenetazzo** [comment]
a quanto abbiamo detto questo non lo facciamo
