### ISSUE TITLE
considerare di usare il GET per i form admin

### ISSUE THREAD

**Issue by LewentalDigital** [Gruppo-TecWeb/Codice#207]
Per migliorare l'esperienza torna indietro/avanti

- [ ] rivedere il torna indietro (button o link?) , che torni indietro solo se provengo da una nostra pagina

**Comment by LewentalDigital** [comment]
@abenetazzo questa si puo' chiudere, in teoria e' gia' implementata??

**Comment by abenetazzo** [comment]
direi di sì
