### ISSUE TITLE
Warning nella pagine Admin

### ISSUE THREAD

**Issue by rzaupa** [Gruppo-TecWeb/Codice#243]
Sono in develop (aggiornato) e ho aggiornato anche il db.
Pagina profilo dell'admin:
<img width="378" alt="Screenshot 2024-06-06 181838" src="https://github.com/Gruppo-TecWeb/Codice/assets/126966421/fb680447-476c-464f-b4e5-3b1ea37c07b0">
pagina "Home" dell'admin:
<img width="408" alt="Screenshot 2024-06-06 181922" src="https://github.com/Gruppo-TecWeb/Codice/assets/126966421/b3ec7a95-97fa-48c4-bfec-e87bca9eaf42">

**Comment by abenetazzo** [comment]
ho trovato un bug diverso in realtà, probabilmente dovuto a qualche merge, mi dava un errore su una query che ho sistemato.

quello che segnali tu a me non risulta, ho provato con diversi tipi di utente e a me non genera nessun warning. prova a fare nuovamente un pull e a ricreare il database da zero, magari c'è qualcosa che non si è aggiornato correttamente.
