### ISSUE TITLE
Errori validatore per la pagina Home

### ISSUE THREAD

**Issue by rzaupa** [Gruppo-TecWeb/Codice#245]
Ti riporrto anche i warning nel dubbio, alcuni sono errori banali (come l'uso di 11 Giugno 2024 come valore di datetime) altri un po' piu' da ragionarci. 
<img width="572" alt="Screenshot 2024-06-07 112222" src="https://github.com/Gruppo-TecWeb/Codice/assets/126966421/79f1d4a2-033f-4348-9dfa-49875fba4f36">
Se vuoi provare il validatore usato è il solito: https://validator.w3.org/

In aggiunta a questo ARC Toolkit mi segnala :

<img width="1080" alt="Screenshot 2024-06-07 121348" src="https://github.com/Gruppo-TecWeb/Codice/assets/126966421/347a7054-91d9-4279-83d3-c495df8a4f89">

Quindi in piu' riporta 
`<video aria-label="Video di presentazione del collettivo" aria-details="#video-descrizione" controls="" autoplay="" loop="" muted="" poster="assets/media/poster.jpg" width="1080" height="1920" controlslist="nodownload" oncontextmenu="return false;"></video>`

**Comment by abenetazzo** [comment]
il tag time l'ho sistemato io assieme agli altri nelle pagine admin nella pr #257
