### ISSUE TITLE
Usare funzioni native per formattare date e rimuovere funzioni create ad hoc

### ISSUE THREAD

**Issue by LewentalDigital** [Gruppo-TecWeb/Codice#25]

**Comment by rzaupa** [comment]
Non ci sono funzioni native per formattare date

**Comment by LewentalDigital** [comment]
> Non ci sono funzioni native per formattare date

Ma scusa @rzaupa, non le hai utilizzate già in #176 ?? 
Comunque non trovo più quelle funzioni create ad hoc
