### ISSUE TITLE
Pagina registrati?

### ISSUE THREAD

**Issue by abenetazzo** [Gruppo-TecWeb/Codice#259]
Apro questa issue per capire cosa fare.
Attualmente abbiamo una pagina di registrazione (registrati) esistente ma alla quale nessuno può accedere in quanto non è linkata da nessuna parte. Vogliamo metterla o la togliamo dalla consegna del progetto?

**Comment by LewentalDigital** [comment]
Secondo me spostiamola post progetto, ci dà lavoro in più di cui non abbiamo bisogno ora

**Comment by abenetazzo** [comment]
Allora rimuovo i due file.
