### ISSUE TITLE
Total validator Eventi

### ISSUE THREAD

**Issue by rzaupa** [Gruppo-TecWeb/Codice#260]
Dettaglio per l'accessibilità:
<img width="377" alt="Screenshot 2024-06-08 130309" src="https://github.com/Gruppo-TecWeb/Codice/assets/126966421/906c4fce-1b4e-4999-93d5-b98d13cdcd67">

**Comment by abenetazzo** [comment]
stesso problema di #261, applico la stessa soluzione
