### ISSUE TITLE
Total Validator Classifiche

### ISSUE THREAD

**Issue by rzaupa** [Gruppo-TecWeb/Codice#261]
Suggerimenti per l'accessibilità:
<img width="535" alt="Screenshot 2024-06-08 131718" src="https://github.com/Gruppo-TecWeb/Codice/assets/126966421/d8c1cc3f-dc45-4ecd-954b-40c42ac7d8a8">
<img width="612" alt="Screenshot 2024-06-08 131819" src="https://github.com/Gruppo-TecWeb/Codice/assets/126966421/177a771c-384e-4b60-8ec8-f0d57a0c4147">

**Comment by abenetazzo** [comment]
Nella pagina vedo 4 elementi con tag nav:
- aiuti alla navigazione (con attributo aria-label, quindi ok);
- menu (con attributo aria-labelledby, quindi ok);
- breadcrumbs (con attributo aria-label, quindi ok);
- skip filtri.

Immagino la segnalazione sia per l'ultimo punto, aggiungo un attributo aria-label per sistemare.

Per la segnalazione successiva tolgo la separazione dei fieldset, in effetti non ha molto senso.
