### ISSUE TITLE
Total validator gestione classifiche

### ISSUE THREAD

**Issue by rzaupa** [Gruppo-TecWeb/Codice#288]
Dopo aver tolto un po' di controlli finalmente riesco a testare la pagina con total validator (intendo gestione-classifiche.php). Segnalo un errore e un warning.
Riga 59
<img width="302" alt="Screenshot 2024-06-09 191719" src="https://github.com/Gruppo-TecWeb/Codice/assets/126966421/d5e68db4-09ef-4e98-abef-6946fe8807b8">
Riga 68
<img width="527" alt="Screenshot 2024-06-09 191603" src="https://github.com/Gruppo-TecWeb/Codice/assets/126966421/022f3e88-76e9-4fa8-b837-f4723c859dde">

**Comment by abenetazzo** [comment]
L'errore l'ho risolto facilmente, il legend vuoto mi fa strano, viene riempito da php, come sei arrivato ad una pagina col legend vuoto?

**Comment by rzaupa** [comment]
Ho tolto
`if (!isset($_SESSION["login"])) {
    header("location: ../login.php");
    exit;
}`

e anche 

`else {
        header("location: classifiche.php");
        exit;
    }`
   alla riga 162
   
   è un problema ?

**Comment by abenetazzo** [comment]
No, non è un problema, e di per se non dovrebbe causare una legend vuota. Avendo tolto questi controlli immagino tu sia andato alla pagina gestione-classifiche.php (come anche per le altre pagine nelle altre issue) digitando l'url direttamente, senza seguire un percorso dalle altre pagine, giusto?

In questo caso è normale che la legend sia vuota, come ti dicevo prima viene popolata dal php in funzione del fatto che si stia modificando un elemento già esistente (e quindi viene scritto modifica ...) oppure si stia aggiungendo un nuovo elemento (e quindi viene scritto aggiunta ...). Durante la normale navigazione non sarebbe mai vuoto, quindi non credo sia un problema.

**Comment by rzaupa** [comment]
Comunque l'aggiunta e la modifica dovrebbe essere su due file diversi in questo modo sono sarebbero facilmente testabili e poi anche per il fatto che sono due pagine distinte e non la stessa pagina che si adatta. Il sorgente da questi form non è possibile ottenerlo quindi non è testabile

**Comment by abenetazzo** [comment]
Non mi sembra molto sensato sdoppiare, puramente allo scopo di semplificare i test, una pagina che deve gestire esattamente gli stessi campi e cambia solo per alcune voci che sono gestibili perfettamente tramite PHP (lo facciamo per l'intero contenuto della pagina...). Sdoppiare le pagine vorrebbe dire complicare in modo esponenziale la manutenibilità del sito, per ogni variazione su campi o contenuti bisognerebbe lavorare parallelamente su due pagine distinte.

Il sorgente è facilmente ottenibile, basta aprire la pagina come farebbe un utente normale, arrivandoci dalle altre pagine, in questo caso partendo da admin/classifiche.php e testando separatamente la modifica di una classifica e l'aggiunta di una nuova classifica (come faresti anche nel caso di due file distinti). Non ci vedo nulla di complicato, tantomeno impossibile.

**Comment by rzaupa** [comment]
> Non mi sembra molto sensato sdoppiare, puramente allo scopo di semplificare i test, una pagina che deve gestire esattamente gli stessi campi e cambia solo per alcune voci che sono gestibili perfettamente tramite PHP (lo facciamo per l'intero contenuto della pagina...). Sdoppiare le pagine vorrebbe dire complicare in modo esponenziale la manutenibilità del sito, per ogni variazione su campi o contenuti bisognerebbe lavorare parallelamente su due pagine distinte.
> 
> Il sorgente è facilmente ottenibile, basta aprire la pagina come farebbe un utente normale, arrivandoci dalle altre pagine, in questo caso partendo da admin/classifiche.php e testando separatamente la modifica di una classifica e l'aggiunta di una nuova classifica (come faresti anche nel caso di due file distinti). Non ci vedo nulla di complicato, tantomeno impossibile.

"Puramente allo scopo di semplificare i test" non è vero. Mi chiedevo già da un po' se avesse senso aprire la stessa pagina ("gestione classifica") che cambia (solo nel contenuto) a seconda di che pulsante clicchi ("modifica" o "aggiunta") quando dal punto di vista teorico dovrebbero essere "evidentemente" due pagine differenti, per breadcrumb e per titolo. Questo riguarda ovviamente non solo classifiche ma anche le altre pagine. Questione non banale e da non sottovalutare.... ad esempio vedi https://web.math.unipd.it/accessibility/dettaglio.html?ID=3. Io direi da ridiscutere in un'altra issue. 

In ogni caso l'errore segnalato da Total Validator non c'è
