### ISSUE TITLE
Rivedere la struttura del sito

### ISSUE THREAD

**Issue by rzaupa** [Gruppo-TecWeb/Codice#295]
https://gsnedders.html5.org/outliner/

Chiaramente guardando anche solo la Home , la gerarchia non c'è e/o è stata fatta male
<img width="234" alt="Screenshot 2024-06-10 155015" src="https://github.com/Gruppo-TecWeb/Codice/assets/126966421/6968b8e0-fb40-4028-baec-240cd5a00812">

Non passa il test https://web.math.unipd.it/accessibility/dettaglio.html?ID=8 che sarebbe livello AAA (quindi opzionale)

**Comment by LewentalDigital** [comment]
Le Untitled Section sono gli aiuti alla navigazione che sono presenti all'interno di nav non visibili normalmente ma vengono compresi nell'outline del sito, ignorando quelli la outline è abbastanza chiara riguardo ai contenuti
Se non lo credi fammi capire che risultato vorremmo.

**Comment by abenetazzo** [comment]
Magari sarebbe utile mettere dei nomi più specifici alle issue... leggere "rivedere la struttura del sito" mi ha fatto perdere qualche anno di vita...
