### ISSUE TITLE
Utilizzo di title per un elemento non interattivo nella pagina modalità

### ISSUE THREAD

**Issue by rzaupa** [Gruppo-TecWeb/Codice#300]
<img width="424" alt="Screenshot 2024-06-12 151714" src="https://github.com/Gruppo-TecWeb/Codice/assets/126966421/d89320db-4af5-4cba-8c4a-6111a1e36898">

Sarebbe forse meglio una soluzione di questo tipo:
```
<p id="descrizione-lista" class="sr-only">Lista delle modalità con successive spiegazioni.</p>
<dl id="lista_battle" aria-describedby="descrizione-lista">
  <!-- Contenuto della lista -->
</dl>
```

**Comment by T-Brex** [comment]
cosa va a indicare la classe sr-only?

**Comment by rzaupa** [comment]
"screen reader only" , in effetti noi l'abbiamo definita così:
<img width="182" alt="Screenshot 2024-06-12 152751" src="https://github.com/Gruppo-TecWeb/Codice/assets/126966421/96c9751f-1039-4f21-bb4c-2868f110d565">

**Comment by T-Brex** [comment]
dio poi io non sapevo dell'esistenza, ho sempre usato NavigationHelp

**Comment by rzaupa** [comment]
> dio poi io non sapevo dell'esistenza, ho sempre usato NavigationHelp



> dio poi io non sapevo dell'esistenza, ho sempre usato NavigationHelp

in effetti credo cambi poco, si può usare anche NavigationHelp credo

**Comment by T-Brex** [comment]
sisi, ma a sto punto mi sembra più corretto con screenReaderOnly
