### ISSUE TITLE
Decidere/rivedere il comportamento dei form lato admin

### ISSUE THREAD

**Issue by rzaupa** [Gruppo-TecWeb/Codice#301]
L'immagine del profilo così grande non ha alcun senso, inoltre da mobile è tutto stravolto e mi pare che sia l'unica pagina che si comporti così

Poi ne approfitto per dire che è l'unico form che non ti reindirizza (dopo averlo compilato) alla pagina di partenza mi pare. Non c'entra per il design però ecco è una segnalazione

<img width="160" alt="Screenshot 2024-06-12 152612" src="https://github.com/Gruppo-TecWeb/Codice/assets/126966421/b081dce2-57b1-43c2-a0d1-27fd553253ef">

**Comment by abenetazzo** [comment]
> L'immagine del profilo così grande non ha alcun senso, inoltre da mobile è tutto stravolto e mi pare che sia l'unica pagina che si comporti così
La parte di stile in effetti manca per tutta l'area admin, è già assegnata nella issue #144 

> Poi ne approfitto per dire che è l'unico form che non ti reindirizza (dopo averlo compilato) alla pagina di partenza mi pare. Non c'entra per il design però ecco è una segnalazione
Non ho capito cosa intendi dire... in questa pagina non mi sembra ci siano form.

**Comment by rzaupa** [comment]
> > L'immagine del profilo così grande non ha alcun senso, inoltre da mobile è tutto stravolto e mi pare che sia l'unica pagina che si comporti così
> 
> La parte di stile in effetti manca per tutta l'area admin, è già assegnata nella issue #144
> 
> > Poi ne approfitto per dire che è l'unico form che non ti reindirizza (dopo averlo compilato) alla pagina di partenza mi pare. Non c'entra per il design però ecco è una segnalazione
> 
> Non ho capito cosa intendi dire... in questa pagina non mi sembra ci siano form.

Intendevo il form di modifica profilo. 
Il fatto che manchi tutto lo stile dell'area admin è una cosa che si sa ? Sarebbe un po' urgente

**Comment by abenetazzo** [comment]
Sì, il fatto che manchi tutto lo stile dell'area admin è una cosa che si sa, come ti dicevo se ne era fatto carico seba nella issue #144 ma immagino che abbia un sacco di cose da fare vedendo le issue, quasi quasi me ne faccio carico io, almeno faccio il grosso poi in caso lui sistema quello che c'è da sistemare.

Per l'altro discorso mi sembra che sia in linea con gli altri form delle altre pagine. Quando viene fatta una modifica e viene premuto il tasto conferma si rimane sulla stessa pagina così si vedono le modifiche effettuate e se ne possono fare delle altre in caso.

**Comment by rzaupa** [comment]
> Sì, il fatto che manchi tutto lo stile dell'area admin è una cosa che si sa, come ti dicevo se ne era fatto carico seba nella issue #144 ma immagino che abbia un sacco di cose da fare vedendo le issue, quasi quasi me ne faccio carico io, almeno faccio il grosso poi in caso lui sistema quello che c'è da sistemare.
> 
> Per l'altro discorso mi sembra che sia in linea con gli altri form delle altre pagine. Quando viene fatta una modifica e viene premuto il tasto conferma si rimane sulla stessa pagina così si vedono le modifiche effettuate e se ne possono fare delle altre in caso.

Lo stile di tutta la parte admin è una grossa feature (forse la piu' grossa), c'è bisogno di farla al piu' presto

Se guardo gli altri form (ad esempio) aggiungi evento è evidente che non si comporti allo stesso modo una volta che clicchi conferma, quindi direi che non è in linea con le altre pagine

**Comment by abenetazzo** [comment]
Quando fai un'aggiunta torni indietro, per poter fare eventuali altre aggiunte, ma nella pagina di modifica del profilo non si fa nessun'aggiunta, ma solo modifiche appunto. Anche nelle altre pagine quando modifichi un elemento già presente una volta premuto conferma si rimane sulla stessa pagina per vedere le modifiche apportate, come anche nella pagina di modifica del profilo. Mi sembra coerente, no?

**Comment by rzaupa** [comment]
> Quando fai un'aggiunta torni indietro, per poter fare eventuali altre aggiunte, ma nella pagina di modifica del profilo non si fa nessun'aggiunta, ma solo modifiche appunto. Anche nelle altre pagine quando modifichi un elemento già presente una volta premuto conferma si rimane sulla stessa pagina per vedere le modifiche apportate, come anche nella pagina di modifica del profilo. Mi sembra coerente, no?

Quindi logica diversa per "modifica" e "aggiunta" ? non l'avevo notato, dunque direi che un problema dato che ha poco senso. "_quando modifichi un elemento già presente una volta premuto conferma si rimane sulla stessa pagina per vedere le modifiche apportate_ "
ma non vale lo stesso quando aggiungi ? quando aggiungi non va bene rimanere sulla stessa pagina per quale motivo ? non posso aver sbagliato anche ad inserire qualche info nell'aggiungi ? e poi pensandoci la modifica potrebbe essere la stessa cosa dell'aggiungi (ad esempio manca un'immagine per cui l'unica cosa che fai è "aggiungi informazione").
Come vedi le logiche di "modifica" e di "aggiunta" si intrecciano e non hanno bisogno di comportamenti diversi, almeno secondo me. In entrambi i casi in realtà si potrebbe gestire con una finestra di dialogo che ti chiede se va bene la modifica o l'aggiunta ma ormai non c'è piu' tempo. A sto punto direi di omologare, per la modifica e per l'aggiunta dopo la conferma si torna alla pagina di partenza ?

**Comment by abenetazzo** [comment]
Inizialmente avevo pensato a due comportamenti diversi perchè ho immaginato che quando uno aggiunge un elemento è più probabile che voglia aggiungerne altri o vedere l'effetto della sua aggiunta e quindi il nuovo elemento in mezzo agli altri, mentre se ha fatto una modifica è più probabile debba fare altre modifiche o voglia vedere le modifiche effettuate. Se credi sia meglio omologare i due comportamenti mi sta bene, non sono particolarmente convinto di una soluzione piuttosto che dell'altra...

Quale comportamento adottare? Diciamo che questo è sempre stato un argomento discusso, non so effettivamente cosa sia meglio... Ha senso tornare alla pagina di provenienza per poter modificare/aggiungere altri elementi, ma ha anche senso rimanere sulla stessa pagina per vedere le modifiche/aggiunte effettuate e poterne fare delle altre. Secondo te cosa sarebbe meglio?

**Comment by LewentalDigital** [comment]
Ufff, decisione difficile
Non si puo' applicare a tutte le pagine una regola unica, la modifica del profilo dovrebbe riportare alla pagina profilo, ma la modifica di un evento dovrebbe lasciarti li facendoti vedere i cambiamenti che hai fatto
Nel frattempo va bene applicare l'idea di rich, confermare riporta alla pagina precedente

**Comment by rzaupa** [comment]
> Inizialmente avevo pensato a due comportamenti diversi perchè ho immaginato che quando uno aggiunge un elemento è più probabile che voglia aggiungerne altri o vedere l'effetto della sua aggiunta e quindi il nuovo elemento in mezzo agli altri, mentre se ha fatto una modifica è più probabile debba fare altre modifiche o voglia vedere le modifiche effettuate. Se credi sia meglio omologare i due comportamenti mi sta bene, non sono particolarmente convinto di una soluzione piuttosto che dell'altra...
> 
> Quale comportamento adottare? Diciamo che questo è sempre stato un argomento discusso, non so effettivamente cosa sia meglio... Ha senso tornare alla pagina di provenienza per poter modificare/aggiungere altri elementi, ma ha anche senso rimanere sulla stessa pagina per vedere le modifiche/aggiunte effettuate e poterne fare delle altre. Secondo te cosa sarebbe meglio?

lato test di accessibilità non ci sono indicazioni in nessuno dei due sensi, forse (ipotizzo) si rompe una convenzione interna per cui il comportamento diverso dei due form può essere un comportamento inatteso per questo dico di omologare (https://web.math.unipd.it/accessibility/dettaglio.html?ID=145) . Anche se comunque è un po' tirata, se non abbiamo tempo di sistemare si può anche lasciare perdere forse, come vi trovate meglio. 
L'importante sarebbe dunque trovare uno dei due modi forse come dice @LewentalDigital è la soluzione migliore, cioè  confermare riporta alla pagina precedente
