### ISSUE TITLE
Per gli elementi button ci devono essere label o aria-label nella pagina beats

### ISSUE THREAD

**Issue by rzaupa** [Gruppo-TecWeb/Codice#302]
Secondo il regolamento gaggi: 
<img width="815" alt="Screenshot 2024-06-12 155553" src="https://github.com/Gruppo-TecWeb/Codice/assets/126966421/83c3776f-87e7-4d30-8ee6-e4860a65e104">

Lo segnala anche ARC toolkit

<img width="415" alt="Screenshot 2024-06-12 155737" src="https://github.com/Gruppo-TecWeb/Codice/assets/126966421/469843e2-3c68-4921-9bda-e2f321f20290">

**Comment by T-Brex** [comment]
per come avete modificato la pagina prima della consegna del concorso, vedo che il bottone ha sia aria-hidden="true" sia tabindex="-1"
ciò mi fa presuporre che quel tasto non sarà mai utilizzato da i non vedenti, perciò ritengo che non sia necessaria nessuna label/aria-label

**Comment by T-Brex** [comment]
l'audio descrizione è sempre presente, infatti se usi lo screen reader, vedrai che se esplori la pagina con le freccette, tra un beat e l'altro, c'è l'audio descrizione

**Comment by rzaupa** [comment]
> l'audio descrizione è sempre presente, infatti se usi lo screen reader, vedrai che se esplori la pagina con le freccette, tra un beat e l'altro, c'è l'audio descrizione

Allora ha ancora meno senso.... il non vedente perché deve sorbirsi l'audio descrizione in ogni caso e il vedente no ? Per altro al non vedente non è un problema se non si becca l'audio descrizione. Penso che il fatto che per tutti sia raggiungibile tramite bottone sia la cosa piu' giusta, o no ?

**Comment by T-Brex** [comment]
l'idea di sbeba è che i non vedenti possono passare da un beat all'altro e in caso ascoltare la descrizione attraverso il "tab"!
 Perciò non è esattamente vero che il non vedente si deve sorbire tutto!

**Comment by LewentalDigital** [comment]
Rich, secondo te potremmo implementare il bottone anche per i non vedenti?
E cosa fa quando lo clicca? porta il focus sulla descrizione??

**Comment by T-Brex** [comment]
- [ ] `<button class="btnDesc" aria-hidden="true" tabindex="-1">` =>`<button class="btnDesc">`
- [ ] `<span class="descBeats" data-show="false">` => `<span class="descBeats" data-show="false" aria-hidden="true">` che diventerà `<span class="descBeats" data-show="true" aria-hidden="false">` al click del pulsante dell'audio descrizione
- [ ] `<a href="#audio" tabindex="-1" aria-hidden="true">
                <span class="navigationHelp">Vai al <span lang="en">player</span> della canzone</span>
            </a>` dovrà essere non più prima di `<span class="descBeats" data-show="false" aria-hidden="true">` ma dopo, in questo modo l'ordine di letture dello screen reader è

1. nome del beat
2. tasto play/stop
3. durata beat
4. descrizione beat
5. Jump al player audio

**Comment by rzaupa** [comment]
> @rzaupa , secondo te potremmo implementare il bottone anche per i non vedenti? E cosa fa quando lo clicca? porta il focus sulla descrizione??

cioè il fatto è che non toglierei informazioni ai non vedenti, non ne vedo il senso, non siamo inclusivi, dici che è un problema se porta il focus sulla descrizione ?

**Comment by rzaupa** [comment]
> * [ ]  `<button class="btnDesc" aria-hidden="true" tabindex="-1">` =>`<button class="btnDesc">`
> * [ ]  `<span class="descBeats" data-show="false">` => `<span class="descBeats" data-show="false" aria-hidden="true">` che diventerà `<span class="descBeats" data-show="true" aria-hidden="false">` al click del pulsante dell'audio descrizione
> * [ ]  `<a href="#audio" tabindex="-1" aria-hidden="true">`
>   `<span class="navigationHelp">Vai al <span lang="en">player</span> della canzone</span>`
>   `</a>`
>   dovrà essere non più prima di
>   `<span class="descBeats" data-show="false" aria-hidden="true">`
>   ma dopo, in questo modo l'ordine di letture dello screen reader è
> 
> 1. nome del beat
> 2. tasto play/stop
> 3. durata beat
> 4. descrizione beat
> 5. Jump al player audio

ci può stare (?), chiedo conferma a @LewentalDigital , unica cosa è il terzo punto cioè è necessario mettere il salto al player prima della descrizione ? penso comunque sia abbastanza indifferente

**Comment by T-Brex** [comment]
no, il salto lo volevo mettere alla fine, dopo descrizione beat, però in effetti è abbastanza indifferente, potrei omettere il il terzo punto(?)
