### ISSUE TITLE
separazione tra contenuto e comportamento non rispettata nel db

### ISSUE THREAD

**Issue by rzaupa** [Gruppo-TecWeb/Codice#314]
L'immagine parla da sola
<img width="667" alt="Screenshot 2024-06-15 163651" src="https://github.com/Gruppo-TecWeb/Codice/assets/126966421/9e3b5afd-1c54-426c-bbd1-4289eff2295f">

Ricordo che tra i requisiti _**obbligatori**_ c'è:

>  il sito web deve rispettare la completa separazione tra contenuto, presentazione e comportamento;

**Comment by abenetazzo** [comment]
Separazione tra contenuto, presentazione e comportamento significa appunto tra contenuto (HTML), presentazione (CSS) e comportamento (PHP/JavaScript).

Non capisco cosa c'entri una query di popolamento del database...

**Comment by rzaupa** [comment]
Grave devo dire... un db che dipende da come vengono rappresentati i dati non ti fa venire nessun dubbio ? E se io volessi usare i dati in un altro modo ? (Esempi banali : uso i dati in un if, il db viene usato non per un sito web, ...)
La separazione delle responsabilità è chiaramente compressa, più evidente di così...

**Comment by abenetazzo** [comment]
Mi sa che qua stai dicendo qualche cavolata... Il db non dipende da nulla, e i dati possono essere usati in qualsiasi modo. Da quando in qua il contenuto di un campo di un database influisce sulle dipendenze?? Non cerchiamo problemi dove non ci sono per cortesia...

**Comment by abenetazzo** [comment]
I tag span sono stati inseriti per ovviare ai problemi legati all'accessibilità, non ci sarebbe altro modo per segnalare con gli attributi lang eventuali parole in lingua inglese (o altre lingue), se preferisci li possiamo togliere ma credo che i problemi di accessibilità che verrebbero introdotti penalizzerebbero il voto.

**Comment by rzaupa** [comment]
Ok, non c'è bisogno di indugiare oltre, assegno la issue a me e approfondirò il problema (in ogni caso la issue tratta di un requisito obbligatorio, se non rispettato vale l'insufficienza automatica)

**Comment by abenetazzo** [comment]
> ha come scopo quello di interagire con il db che dunque fa parte del comportamento (cosa fa se no ? Php da solo a che serve ? )

Altra cavolata... Il DB nulla ha a che vedere con il comportamento, altrimenti stessa cosa varrebbe anche per l'HTML e tutti gli altri elementi con cui interagisce. Non mischiamo cavoli e patate... Il PHP è comportamento, il DB è persistenza dei dati, ed entrambi hanno molti altri usi anche senza l'altro, dire che il PHP senza il DB non serve a nulla mi sembra molto riduttivo oltre che gravemente sbagliato.

**Comment by abenetazzo** [comment]
> Ok, non c'è bisogno di indugiare oltre, assegno la issue a me e approfondirò il problema (in ogni caso la issue tratta di un requisito obbligatorio, se non rispettato vale l'insufficienza automatica)

Ripeto, la issue è sbagliata, il DB non ha nulla a che vedere con il comportamento, stai cercando un problema dove non c'è.

Questa slide della Gaggi parla chiaro...

<img width="973" alt="Screenshot 2024-06-15 alle 19 40 45" src="https://github.com/Gruppo-TecWeb/Codice/assets/79547694/96e0cdd6-9497-4926-9bc5-6dd343af5fb9">

**Comment by abenetazzo** [comment]
> Ok, non c'è bisogno di indugiare oltre, assegno la issue a me e approfondirò il problema (in ogni caso la issue tratta di un requisito obbligatorio, se non rispettato vale l'insufficienza automatica)

Puoi anche assegnartela e togliermela se lo ritieni opportuno, sarebbe stato più utile e maturo se mi avessi dato argomentazioni valide e magari anche una tua opinione su possibili alternative.

**Comment by rzaupa** [comment]
Le mie argomentazioni le ho già esposte, non siamo d'accordo, continuerei anche ma i toni non mi sembrano adatti per maturare qualcosa di costruttivo e non di "distruttivo". Chiudo la issue e approfondisco per conto mio.

**Comment by abenetazzo** [comment]
Non credo di aver usato toni inadatti, se così è stato mi scuso, non era mia intenzione.

Il problema sta nel fatto che non hai argomentato, hai semplicemente dato affermazioni a mio avviso scorrette presupponendo di affermare verità assolute, oltre al fatto che non hai proposto alcuna alternativa che secondo te sarebbe stata migliore. Non dico di avere io la verità, anzi, probabilmente sbaglio anche io e di sicuro ci sono modi molto migliori di fare quello che faccio e che ho fatto.
Probabilmente, secondo me, il modo migliore di porsi, specie tra colleghi studenti, sarebbe quello di confrontarsi e trovare le migliori soluzioni assieme.

In ogni caso va bene, non aggiungo altro, spero di averti espresso in modo chiaro e obiettivo le mie perplessità, fai pure le tue valutazioni.
