### ISSUE TITLE
Pagina Eventi: lo screen reader legge sia "Salta i filtri e vai ai risultati" sia "Salta ai risultati"

### ISSUE THREAD

**Issue by T-Brex** [Gruppo-TecWeb/Codice#323]
1. lo screen reader legge sia "Salta i filtri e vai ai risultati" sia "Salta ai risultati"
> ` <nav id="filtri-skip" aria-label="Salta i filtri e vai ai risultati">`
> `    <a href="#risultati-eventi" class="navigationHelp">Salta ai risultati</a>`
> `</nav>`

suggerisco di eliminare l'aria-label e di testare successivamente

2. input type="date" all focus del giorno o mese o anno dice "spin _numero_", può essere reso migliore?

**Comment by rzaupa** [comment]
Per il secondo punto non è un problema, abbiamo provato con lo screen reader e sembra tutto a posto, spin è il tipo di input
