### ISSUE TITLE
gestione dell'attributo lang 

### ISSUE THREAD

**Issue by rzaupa** [Gruppo-TecWeb/Codice#331]
gestione interessante di pop tech anche se non ottimale, però dal punto di vista logico è corretta perchè separi la logica di persistenza da quella di presentazione.

<img width="412" alt="Screenshot 2024-06-18 092730" src="https://github.com/Gruppo-TecWeb/Codice/assets/126966421/21daf618-ac16-45c3-ba71-a00ece47343d">

e nel db salvano i dati così 
<img width="429" alt="Screenshot 2024-06-18 092802" src="https://github.com/Gruppo-TecWeb/Codice/assets/126966421/c30fb9bb-37e5-4aff-9e1e-fa0acb79c236">

in questo modo il database non dipende come detto da come verranno rappresentati i dati e il problema viene risolto, anche se bisogna ricordarsi tramite php di togliere [en] [/en]. Tuttavia, è la soluzione piu' interessante e adatta che ho trovato finora. Di certo è meglio di lasciare così oppure di togliere tutti i lang come avevate proposto. Poi ovviamente c'è la questione tempistiche da valutare.

Ditemi se vi può andare bene o se trovate altro

**Comment by abenetazzo** [comment]
Questo sicuramente risolve il problema dei tag HTML nel DB, poi ovviamente bisognerà spiegare all'utente l'utilizzo di questo pattern per contrassegnare parole in lingua straniera, cosa non semplice (ad esempio potrebbe mettere una stringa errata per la lingua, come eng o us al posto di en, o altre cose simili).
Mi viene un dubbio più preoccupante però... Vedendo come hanno fatto loro, se non erro, hanno inserito i tag HTML direttamente nel codice Javascript, questo non violerebbe il principio di separazione tra contenuto e comportamento?

**Comment by LewentalDigital** [comment]
Alla fine cambia poco dall'usare direttamente tag html, non credete?

**Comment by abenetazzo** [comment]
> Alla fine cambia poco dall'usare direttamente tag html, non credete?

Anche secondo me alla fine non cambia molto... Visti i tempi stretti, cosa facciamo?
