### ISSUE TITLE
Controllo input filtri eventi lato client e server

### ISSUE THREAD

**Issue by LewentalDigital** [Gruppo-TecWeb/Codice#335]

**Comment by abenetazzo** [comment]
Dopo lo vediamo assieme... ma secondo me sia sulla pagina eventi che sulla pagina classifiche i controlli che servono ci sono già. Trattandosi di select e date come input lato client non vedo utile fare alcun controllo, può essere inserito qualcosa di non valido solamente manipolando il codice html, non mi sembra utile controllare questa cosa per mandare un messaggio d'errore user friendly. Lato server i controlli ci sono, infatti se vengono inviati dati non validi si viene reindirizzati alla pagina di errore 404.

Voi cosa ne pensate?
