### ISSUE TITLE
Creazione dashboard area admin 

### ISSUE THREAD

**Issue by LewentalDigital** [Gruppo-TecWeb/Codice#56]
Per utente base, pagina in stile profilo github:
- [x] immagine di profilo grande
- [ ] ranking classifica attuale
- [ ] prossimo evento a cui sono iscrittto
- [x] link a modifica profilo

Per utente admin:
- [x] numero eventi in programma
- [x] prossimo evento in programma e numero iscritti
- [x] eventi passati presenti in una classifica ma senza punteggi
- [x] numero utenti attivi

**Comment by abenetazzo** [comment]
vedi anche issue #151
