### ISSUE TITLE
Deve essere presente un audio descrizione per tutti i contenuti preregistrati

### ISSUE THREAD

**Issue by rzaupa** [Gruppo-TecWeb/Codice#73]
Riferimento qui : https://web.math.unipd.it/accessibility/dettaglio.html?ID=41, qui : https://web.math.unipd.it/accessibility/dettaglio.html?ID=35 e qui: https://web.math.unipd.it/accessibility/dettaglio.html?ID=31

**Comment by T-Brex** [comment]
@rzaupa in teoria youtube ha i sottotitoli generati automaticamente, quindi c'è il testo in real-time(AA o forse AAA), inoltre l'audio descrizione c'è dato che sarebbe la spiegazione della modalità(A)
